title: "PitAIcos do Brasileirão"
description: "PitAIcos, análises e previsões da rodada do Brasileirão com Inteligência Artificial"
author: "Alex O'Mota"
markdown: kramdown
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
